### ISSUE TITLE
Example of use for `loadModule`

### ISSUE THREAD

**Issue by pasunboneleve** [target/theta-idl#10]
Hey, Tikhon,

> `<ROOT>` is one of the directories that Theta searches through for modules, based on the Theta path which is set in different ways depending on the target you're compiling to.

Suppose I am going to use `loadModule` in Haskell. Then how is `<ROOT>` set?

**Comment by TikhonJelvis** [comment]
Good question. `loadModule` takes two arguments: the load path and the module name. For example, this is how I use it to load modules in the test suite:

```
loadModule "test/data/transitive" "c"
loadModule "test/data/modules" "importing_foo"
loadModule "test/data/modules" "primitives"
```

I *believe* the relative paths get resolved relative to the root of the project (ie where the `.cabal` file is located), but I'm not 100% sure—now that I think about it, I just relied on that behavior and it seemed to work consistently :P. The underlying code looks paths up relative to your working directory, and I suppose the working directory is set to the project root during compilation.

The Theta executable uses a `THETA_LOAD_PATH` environment variable to search for modules, which you can override with a command-line argument. The Theta load path can have multiple directories separated by `:`; `loadModule` supports this as well to be consistent.
