### ISSUE TITLE
Are comments implemented?

### ISSUE THREAD

**Issue by pasunboneleve** [target/theta-idl#14]
I'm writing a long file to benchmark this library, and suddenly I find I can't comment it. Is there something missing in the documentation or comments are not implemented?

**Comment by TikhonJelvis** [comment]
Comments should be implemented. What kind of error are you seeing?

I did make some changes in the parser shortly before open-sourcing to support documentation comments, and I suppose that could have affected normal comments somehow.

**Comment by pasunboneleve** [comment]
What character do you use to signal commenting?

**Comment by TikhonJelvis** [comment]
C/Java-style comments: `//` for line comments and `/* */` for block comments.

`///` and `/** */` are the form used for documentation comments, so that might lead to a parse error if they're not used right above a definition.

**Comment by TikhonJelvis** [comment]
Looks like I don't have any examples of comments in the README *or* the user guide :confounded:. Should be easy to add though.

**Comment by TikhonJelvis** [comment]
Oh hey, did you end up solving the problem you were having with comments?

**Comment by pasunboneleve** [comment]
My problem was I didn't know what characters to use as comments. I'm using `//` now, no issues, _after_ the `---`. That was a learning exercise too. 😉 Better to have a mention in the docs.

**Comment by TikhonJelvis** [comment]
Good call. I'll add some examples of comments to the documentation. I'll also support comments in the metadata section—that's just an oversight in the parsing code :P
