### ISSUE TITLE
get newtype function

### ISSUE THREAD

**Issue by pasunboneleve** [target/theta-idl#38]
Hi, Tikhon.

Maybe it is somewhere in the code, but from a documentation point of view: If I create a newtype like

```
type MyText = String
```
What is the Haskell function that is then created to unwrap the `Text`? `getMyText`?

**Comment by TikhonJelvis** [comment]
Right now, the generated type doesn't have a field at all:

```
newtype MyText = MyText String
```

Instead, you could pattern match on `MyText` or use `coerce`. Honestly, the latter seems like a better option in modern Haskell than using field accessors as functions.

**Comment by pasunboneleve** [comment]
Thanks! I was wondering if I was doing the right thing. Seems I am!

**Comment by TikhonJelvis** [comment]
Sounds good. I was thinking that it would be neat to make the TH code extensible, letting people easily override behavior like this—but, right now, I have no idea of what a reasonable design for that would look like. Happy to hear any ideas :).
