### ISSUE TITLE
Separate executable and library code

### ISSUE THREAD

**Issue by TikhonJelvis** [target/theta-idl#41]
Based on @istathar's suggestion in [#37][1]

> [as an aside, and worthy of another issue, in a parallel universe I might suggest putting the library in theta/ and the actual Theta binary in theta-tool/ or something (because otherwise people depending on the library have the binary installed in their local work dir every time), but that's a minor detail and not nearly as impactful as the main change above was. This is mostly just disk space]

[1]: https://github.com/target/theta-idl/issues/37#issuecomment-1046416410

**Comment by TikhonJelvis** [comment]
This seems reasonable to me. How do different components work with Stack? Would this be a matter of organizing the executable code as a separate Cabal package, or just a matter of the directory that the executable code is located in?

**Comment by istathar** [comment]
Yes, it would be a separate Cabal package (that would depend on `theta`).
