### ISSUE TITLE
theta-mode doesn't align enum

### ISSUE THREAD

**Issue by pasunboneleve** [target/theta-idl#45]
I'm hitting tab and that's how `theta-mode` wants to align `enum`.
```theta
language-version: 1.0.0
avro-version: 1.0.0

---

type A =
    { a : String
    , b : Int
    }

        enum Blah = HO | HI

```

Using trailing rather than leading commas doesn't make any difference.

**Comment by TikhonJelvis** [comment]
Oh yeah, I added the `enum` keyword to the syntax highlighting but forgot to add it to the indentation code. The whole indentation thing was *very* finicky—maybe treesitter integration will make this easier in the future?—so it'll always be a bit messy, but I can at least fix this particular issue.
