### ISSUE TITLE
UUID can't be imported in Python

### ISSUE THREAD

**Issue by pasunboneleve** [target/theta-idl#64]
I have these files in the same directory:

`name.theta`
```
language-version: 1.1.0
avro-version: 1.1.0

---

type CatName = UUID
```

`animal.theta`
```
language-version: 1.1.0
avro-version: 1.1.0

---

import name

type Cat = {
    name : name.CatName
}
```

`roar.sh`
```bash
#!/usr/bin/env bash

export THETA_LOAD_PATH=${PWD}

theta python -m animal -o py_animal
```

Running `$ ./roar.sh` gives me

```
❯ ./roar.sh
Errors in module definitions:

Error in module ‘name’:
The type ‘name.UUID’ is not defined. 
```

That's surprising. I had no issues with Haskell or Avro code generation.

**Comment by TikhonJelvis** [comment]
Hmm, that's pretty odd.

Given that the Haskell and Avro code generation worked, I don't have an idea off-hand about why the Python code would fail like this. Is it possible that `roar.sh` uses an older build of the `theta` executable?

**Comment by pasunboneleve** [comment]
Yep, that was the case. Thank you for restoring my sanity, @TikhonJelvis !
